# Sample .travis.yml for R projects.
#
# See README.md for instructions, or for more configuration options,
# see the wiki:
#   https://github.com/craigcitro/r-travis/wiki

language: c

os:
  - linux
  #- osx

env:
  global:
    # - R_BUILD_ARGS="--no-test-load --configure-args='--with-mpi-type=OPENMPI --with-mpi-include=/usr/lib/openmpi/include --with-mpi-libpath=/usr/lib/openmpi/lib'"
    - R_BUILD_ARGS="--no-test-load"
    - LD_PRELOAD=/usr/lib/openmpi/lib/libmpi.so

before_install:
  - sudo apt-get install -qq libopenmpi-dev
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap

install:
  - ./travis-tool.sh install_deps

script: ./travis-tool.sh run_tests

after_failure:
  - ./travis-tool.sh dump_logs

notifications:
  email:
    on_success: change
    on_failure: change

sudo: required
