# Sample .travis.yml for R projects.
#
# See README.md for instructions, or for more configuration options,
# see the wiki:
#   https://github.com/craigcitro/r-travis/wiki

language: r

r:
  - devel

os:
  - linux

addons:
  apt:
    packages:
      - libopenmpi-dev

env:
  global:
    - LD_PRELOAD=/usr/lib/openmpi/lib/libmpi.so

r_packages:
  - rlecuyer
  - pbdPROF
  - pbdZMQ

r_build_args: --no-build-vignettes --no-manual --no-test-load --configure-args='--with-mpi-type=OPENMPI --with-mpi-include=/usr/lib/openmpi/include --with-mpi-libpath=/usr/lib/openmpi/lib'

r_check_args: --no-build-vignettes --no-manual --no-test-load --configure-args='--with-mpi-type=OPENMPI --with-mpi-include=/usr/lib/openmpi/include --with-mpi-libpath=/usr/lib/openmpi/lib'

sudo: required

notifications:
  email:
    on_success: never
    on_failure: never
