language: r

branches:
  only:
    - master
    - osx

r:
  # - devel
  - release

os:
  - linux

before_install:
  - sudo apt-get update -q
  - sudo apt-get install -y -q libopenmpi-dev openmpi-bin
  - LD_PRELOAD=/usr/lib/openmpi/lib/libmpi.so
  - mpiexec --version
  - mpicc -showme:incdirs
  - mpicc -showme:libdirs
  - mpicc -showme:compile
  - mpicc -showme:link
  - mpiexec -np 2 hostname
  - cd ../
  - R CMD build --no-resave-data --no-manual --no-build-vignettes pbdMPI

# r_packages:
#   - rlecuyer

install:
  - Rscript -e "install.packages(c('float','rlecuyer','pbdZMQ','pbdPROF'), repos = 'https://cran.r-project.org/')"
  - R CMD check ./pbdMPI_*.tar.gz --as-cran
  - cat ./pbdMPI.Rcheck/pbdMPI-Ex.Rout
  - cat ./pbdMPI.Rcheck/pbdMPI-Ex.timings

script:
  - R CMD INSTALL ./pbdMPI_*.tar.gz

sudo: required
dist: trusty

notifications:
  email:
    on_success: never
    on_failure: never
