# Sample .travis.yml for R projects.
#
# See README.md for instructions, or for more configuration options,
# see the wiki:
#   https://github.com/craigcitro/r-travis/wiki

language: r

r:
  - devel

os:
  - linux

before_install:
  - sudo apt-get update -q
  - sudo apt-get install -y -q libopenmpi-dev openmpi-bin
  - LD_PRELOAD=/usr/lib/openmpi/lib/libmpi.so

r_packages:
  - rlecuyer
  - pbdPROF
  - pbdZMQ

sudo: required
dist: trusty

notifications:
  email:
    on_success: never
    on_failure: never
