language: r

branches:
  only:
    - master
    - osx

r:
  # - devel
  - release

os:
  - linux

before_install:
  - sudo apt-get update -q
  - sudo apt-get install -y -q libopenmpi-dev openmpi-bin
  - LD_PRELOAD=/usr/lib/openmpi/lib/libmpi.so
  - cd ../
  - tar zcvf ./pbdMPI.tar.gz ./pbdMPI

r_packages:
  - rlecuyer

install:
  - R CMD INSTALL ./pbdMPI.tar.gz
  - R CMD check ./pbdMPI.tar.gz

sudo: required
dist: trusty

notifications:
  email:
    on_success: never
    on_failure: never
