language: r

branches:
  only:
    - master
    - osx

r:
  # - devel
  - release

os:
  - linux

before_install:
  - sudo apt-get update -q
  - sudo apt-get install -y -q libopenmpi-dev openmpi-bin
  - LD_PRELOAD=/usr/lib/openmpi/lib/libmpi.so
  - cd ../
  - R CMD build --no-resave-data --no-manual --no-build-vignettes pbdMPI

# r_packages:
#   - rlecuyer

install:
  - Rscript -e "install.packages('rlecuyer', repos = 'https://cran.r-project.org/')"

  # - R CMD INSTALL ./pbdMPI_*.tar.gz
  - R CMD check ./pbdMPI_*.tar.gz --as-cran
  - cat ./pbdMPI.Rcheck/pbdMPI-Ex.Rout
  - cat ./pbdMPI.Rcheck/pbdMPI-Ex.timings

sudo: required
dist: trusty

notifications:
  email:
    on_success: never
    on_failure: never
