# Using AppVeyor's built-in R support
image: Visual Studio 2022

environment:
  R_VERSION: release
  R_ARCH: x64
  RTOOLS_VERSION: 44  # or 45
  USE_RTOOLS: true
  
install:
  # Install MS-MPI
  - ps: Start-FileDownload 'https://download.microsoft.com/download/2/E/C/2EC96D7F-687B-4613-80F6-E10F670A2D97/msmpisetup.exe'
  - MSMpiSetup.exe -unattend
  - ps: Start-FileDownload 'https://download.microsoft.com/download/2/E/C/2EC96D7F-687B-4613-80F6-E10F670A2D97/msmpisdk.msi'
  - msmpisdk.msi /passive
  - set MPI_EXEC=C:\Program Files\Microsoft MPI
  - set MPI_ROOT=C:\Program Files (x86)\Microsoft SDKS\MPI
  - set PATH=%MPI_EXEC%\Bin;%PATH%

build_script:
  # No need to cd into pbdMPI - we're already in the project root
  - Rscript -e "install.packages('remotes', repos='https://cloud.r-project.org')"
  - Rscript -e "remotes::install_deps(dependencies=TRUE)"
  - R CMD build --no-build-vignettes --no-manual --no-resave-data .
  - FOR %%f IN (*.tar.gz) DO R CMD INSTALL %%f
  - FOR %%f IN (*.tar.gz) DO R CMD check %%f --as-cran --no-manual --no-vignettes --no-clean
    