#! /bin/sh
rm -rf ./chm
rm -rf ./config.*
rm -rf ./autom4te.cache
rm -rf ./src/Makevars
rm -rf ./src/Makedeps
rm -rf ./src/Makeconf
rm -rf ./src/*.dylib
rm -rf ./src/*.so*
rm -rf ./src/*.o
rm -rf ./src/*.d
rm -rf ./src/*.dll
rm -rf ./src/*.a
rm -rf ./src/*.rc
rm -rf ./src/*.rds
rm -rf ./src-*
rm -rf ./inst/etc*
rm -rf ./R/zzz.r

rm -rf ./src/fpmpi/*.o
rm -rf ./src/fpmpi/fpmpiconf.h
rm -rf ./src/fpmpi/profiler.h

rm -rf ./inst/doc/
